### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by royteeuwen** [openshift-quickstart/openshift-mongo-flask-example#4]
Following the entire readme.md guide, I get a error 500 page when trying to go to the webservice page.

The logs show this:

[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1] mod_wsgi (pid=285228): Target WSGI script '/var/lib/openshift/52accffe5973caf66700054f/app-root/runtime/repo/wsgi/application' cannot be loaded as Python module.
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1] mod_wsgi (pid=285228): Exception occurred processing WSGI script '/var/lib/openshift/52accffe5973caf66700054f/app-root/runtime/repo/wsgi/application'.
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1] Traceback (most recent call last):
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1]   File "/var/lib/openshift/52accffe5973caf66700054f/app-root/runtime/repo/wsgi/application", line 24, in <module>
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1]     from myflaskapp import app as application
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1]   File "/var/lib/openshift/52accffe5973caf66700054f/app-root/runtime/repo/wsgi/myflaskapp.py", line 2, in <module>
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1]     from flask import Flask
[Sat Dec 14 16:56:26 2013] [error] [client 127.2.168.1] ImportError: No module named flask

I have used the exact commands from the README.MD, and verifiëd on the openshift site itself that it is version 2.6 of python that is installed.

**Comment by vschmidt94** [comment]
It's nearly a year later, but for the record @AritzBi is correct, the correction appears in @dobbymoodge 's repo, not this repo.  Simple enough fix once you find this comment thread.
